### ISSUE TITLE
Move GitRepository to JGit

### ISSUE THREAD

**Issue by fzakaria** [oracle/opengrok#1113]
It would be great to move as many of the external tools to pure java implementations.
a) It would simplify the testing
- JGit for instance provides JUnit test helpers that setup a test repository that gets deleted after test execution. This would remove the need to hanve `ant` scripts create and bundle test repositories.

b) speedup the execution
- No need to call out to external process

c) make setup easier
- No need to figure out the path to Git and more repositories can be by default supported

I've explored swapping GitRepository to JGit and it's definitely feasible. The tough point at the moment is that there are few tests for some of the functions.

**Comment by tarzanek** [comment]
well I would always want a fallback method to not java implementations, but native ones
I have a very bad experience with jgit in jenkins, where I always have because of various bugs to switch back to native git (which I can control the version of)
But obviously your experience might vary, I'd just be cautious about moving everything to java ...
(I guess better would be to have a set of recommended external tool versions ... )

**Comment by tarzanek** [comment]
regarding versions - there is a bug #970 - where basically since hg 3.4 mercurial is not working properly with opengrok ...
so it's really hard to decide to go just for one way (since both seem to have probs long term :( )

**Comment by fzakaria** [comment]
Interesting, I would have thought the inprocess solutions (java/JNI implementations) the way to go.

**Comment by tarzanek** [comment]
Yes, jni would be good too, better than pure java, since the original libs from OS are used ...
Jgit is jni?

**Comment by fzakaria** [comment]
Looks like there are other projects that provide JNI bindings for [libgit](https://github.com/ethomson/jagged)  but nothing worthwhile.

**Comment by vladak** [comment]
With the renamed file handling in Git (issue #1345) we need to make sure that whatever library is chosen supports this functionality.

**Comment by vladak** [comment]
Also, we need to carefully evaluate this in terms of performance and stability. Surely we don't want to switch to library which is not being actively developed and has uncertain future.

**Comment by marcelhuberfoo** [comment]
As far as I checked today for [jgit](https://github.com/eclipse/jgit), it seems to be actively maintained and developed.
jgit also supports [renamed file handling](https://github.com/eclipse/jgit/blob/f3ec7cf3f0436a79e252251a31dbc62694555897/org.eclipse.jgit/src/org/eclipse/jgit/revwalk/FollowFilter.java)
Using [Executor.exec](../blob/master/src/org/opensolaris/opengrok/util/Executor.java#L146) imposes a high system load due to spawning and destroying processes all the time. A lot of which might be massively reduced using a java library to perform git commands.

**Comment by vladak** [comment]
This will be done in multiple phases:
- [x] convert enough of `GitRepository` so that `RepositoryFactory#getRepository()` runs without any command execution (working on this right now, will submit PR soon)
- [ ] annotate
- [ ] bulk of history
- [ ] renamed files handling

Only when all of these are completed the `isWorking()` can be replaced by `return true`.

**Comment by vladak** [comment]
Also, getting the diff of two file revisions should be possible without finding the original name. The `Repository` class and the web app will have to be adapted.

**Comment by vladak** [comment]
This is done, hence closing.
