### ISSUE TITLE
Does opengrok Support cluster based installation

### ISSUE THREAD

**Issue by PawanKulkarniS** [oracle/opengrok#1123]
Dear Gurus,

Does Opengrok support cluster based installation wherein multiple servers are used for indexing and/or multiple servers can be used for just browsing indexed data , something like multiple opengrok servers which keep indexing multiple repos ( say behind a load balancer ) ?

**Comment by tarzanek** [comment]
not yet,
main idea is that browsing data from e.g. hadoop would be definitely feasible (and lucene supports that nicely)
but indexing would still be the same speed ... 
so the question is if this makes sense investing time to - I mean all installations of OpenGrok I saw can handle indexing/serving at the same time very well, but obviously you have a huge installation(a lot of sources, > 200G)  and thousands of users(this is usually a problem, since development groups are rather small - within 100s) then this might be a good project.
Are you willing to invest some time into this?
(I have looked into this in past and it's definitely doable, but more of config job rather than coding)

--
L

**Comment by tulinkry** [comment]
Response given, no other reaction. A candidate for closing

**Comment by vladak** [comment]
I think the idea itself is reasonable and should be explored (possibly as a master thesis) so let's keep this open for now unless there is another issue that describes this better.

**Comment by vladak** [comment]
#779
