### ISSUE TITLE
rewrite shell scripts to Python

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1783]
Given all the tiptoeing around keeping the `OpenGrok` shell script to work on all the ancient/strange shells and the used commands therein to adhere to minimum feature set (#1781), it might be just better to rewrite to Python which seems to be prevalent on todays Unices (dunno about Windows). In the worst case we will have to keep transitioning between the Python languages (version change in Python is really a turnover to different language) but at least they will work the same on all platforms (given the limited set of features that are needed). Last but not least, the coding style of the script will be sort of forced to be common - the style variance of the script today makes me wince sometimes.

**Comment by vladak** [comment]
I've just started rewriting parallel syncing/reindexing script from ksh into Python so having a library to perform reindexing in Python would fit nicely.

Same goes for `Messages`.

**Comment by jelmd** [comment]
Doesn't make sense IMHO. If it is too complex for ksh93 (which I doubt), it should be implemented in the same lang the other/more complicated stuff is implemented, i.e. java.

BTW: Never understood, why all possible properties need to be exposed via CLI options. For simple things, that's certainly nice, but since there are so many [now], it is IMHO much better to use an *rc or properties or init or yaml or whatever file, instead of making things more complicated than they are. A thin wrapper is ok (to pickup all required libs etc.), but that's it. Wrapping the actual stuff 3 times+ is simply not very smart (I guess most opengrok users have already canned their "opengrok invocations" into a script or at least alias, to ensure, that the job gets done in a reliable way ...)

**Comment by ttimasdf** [comment]
I totally agree with .. rewriting! I've been recently working on wrapping OpenGrok in a Docker container. This crappy language spends me days figuring out some hacky solutions for the weird differences between different shells, in my case bash and zsh.
As the script grows larger it is reasonable to move to a more robust language. As for the language, I thought Python is a good choice, for this specific scenario requires convenient string operation. Also points by @jelmd make sense, that we may also need an easy way to configure. I've read the doc and code trying to change a theme, finally got that I might never had a way to it. If the new script provides a way to bootstrap the complicated `configuration.xml`, that would be great 😸

**Comment by vladak** [comment]
@jelmd the same thoughts occurred to me, in the light of #1823. I guess it is necessary to find out what are all the pieces of additional logic in the script (like webapp server detection for deploy) and also see if they can possibly moved to the Java code.

@ttimasdf another reason for moving to Python are the sync scripts (under `tools/sync`) that are written in Python.

**Comment by jelmd** [comment]
@vladak yes, IMHO a simple key=value list line-by-line would help (and thus usable by shell scripts as well as other langs). E.g.  I use ksh93 and invoke it like [opengrok](http://iks.cs.ovgu.de/~elkner/s11/zinstall/files/glassfish/src/opengrok)` -c ~/src/opengrok2.rc update`.  The script is basically the same as the one from the repo, but cut off most of the auto-detect stuff (just assume GF) and added the ability to source in another script, which is basically all I need.

Trying to make the script compatible with every shell on the planet is IMHO not the way to go. It is like keep progging in K&R style ;-). Even younger shells like dash, which is the default shell aka /bin/sh on Ubuntu, is a pretty rudimentary thing - so pain over pain, if one wanna write a little bit more than `echo hello world`.

I've chosen ksh93 instead of bash (or anything else) because it is close enough to the original, avail one every platform as well, but allows to write scripts with much less clutter, has proper CLI option handling, supports neat things like `A+="bla"` instead of `A="${A}bla"`, allows to "embed" sufficient and consistent man page[s] (i.e. not a echo ... based one - another TBD), and proper tracing on demand [by function] ... Absolutely sufficient IMHO. I doubt, that a python script would be/could do it better (and already see the pain wrt. python27, python35, ...).
