### ISSUE TITLE
password not obfuscated for Git repository url when displayed in the Web

### ISSUE THREAD

**Issue by ridderw** [oracle/opengrok#2004]
After indexing some projects the opengrok landing page shows me the projects for which history was created including the repository url, in which the password is visible. Is there an option to have the password obfuscated? (for now we can only access the Git repository through https).

![image](https://user-images.githubusercontent.com/6334409/35855732-461839bc-0b34-11e8-994a-56ba12a04649.png)

**Comment by ridderw** [comment]
Using OpenGrok v1.1-SNAPSHOT rev e578e80026144646af450bdb4d5ba57b8f2de179

**Comment by idodeclare** [comment]
If you are unable to use git SSH, then you might see about configuring the user updating your Git repositories with [git-credential-store](https://git-scm.com/docs/git-credential-store) (and set strict file system permissions for that user's `~/.git-credentials`).

The OpenGrok web server account should not need access to this, because OpenGrok only uses Git commands that read the local repo (e.g., `git-log` and `git-show`). Commands that update repositories — e.g.`git-pull` — are external to OpenGrok.

After setting up `git-credential-store`, you would execute [git-remote](https://git-scm.com/docs/git-remote) `set-url` for those repositories to remove the user and password.

**Comment by ridderw** [comment]
thanks for the response, I will look into this.

**Comment by ridderw** [comment]
Took a look at the suggestion to use the git-credential-store but this mechanism is not an option as it requires someone, at some point, to enter a user-id and password which does not happen in our case. We have an automated clone process running that sets the user-id and password on the url. Personally I think this issue can be seen as being similar to issue #1561 User/password visible in process listing during indexing of SVN repository, only a bit more dramatic as any user that can access the opengrok landing/search page will see the credentials used to clone the repositories.

**Comment by emergie** [comment]
If `git-credentials` mechanism is not suitable, you might create a `~/.netrc` file:
```
machine jenkins01 login riddw password secret
```
and use repo urls with password stripped out: https://riddw@jenkins01/gitbucket/git/root/common.git

**Comment by vladak** [comment]
I guess as a last resort a method for displaying URIs safely can be implemented and used throughout the UI.

**Comment by ridderw** [comment]
I don't think the netrc will work in our setup. We have a server that reads multiple repositories from multiple locations for different users. It doesn't look like netrc is up to this task as it is user bound per machine. Another drawback is that the password in the netrc file is in plain text, although there seems to be a solution for this by decrypting the file and having it decrypted for a git operation, but setting this up is overly complex and error prone.
