### ISSUE TITLE
Allow searching for file names including line numbers

### ISSUE THREAD

**Issue by smehrbrodt** [oracle/opengrok#2041]
When entering a file name like `vcl/opengl/gdiimpl.cxx:49` the `:49` should be treated as line number.

Meaning, it should either be ignored (and the file should be found anyway), or even better, the link should lead directly to the entered line.

Currently the file is not found if it's entered with the line number syntax.

**Comment by tarzanek** [comment]
I think such check would be doable, it could be inserted either to client javascript side to strip away :\d from the end of filepath
(easy fix)
or parsed away by javascript and sent as new field (l ?) which later on is processed by one of the jsps ...
if you want, you can write the patch,
start with https://github.com/oracle/opengrok/blob/master/web/menu.jspf

**Comment by tulinkry** [comment]
isn't it better to strip it in the backend?

**Comment by Orviss** [comment]
I for myself do not like this suggestion very much. 

`vcl/opengl/gdiimpl.cxx:49` will essentialy be tokenized into `vlc`, `/`, `opengl`, `/`, `gdiimpl`, `.`, `cxx:49`, right? (Maybe `/` can be left out etc. (not quite sure)) Then what about the files with name/extension which is the same as a field name?

For example, how do you propose to interpret `defs:123`? Is it a combination of field/term or file_name/line_number? Will this be only specific to the `File Path` input field? If you want to do it properly then we would need to allow something like this: `path:file_path:line_num` in the `Full Search` input field which I believe the default parser will have difficulty with since `:` has special meaning so we would basically need to implement our own extension to the Lucene query grammar, right?

To conclude, I think it is a little counter intuitive to the way how Lucene search works...

**Comment by smehrbrodt** [comment]
I would limit this to the file path field.

**Comment by vladak** [comment]
Actually, my gut feel says "do not implement this in OpenGrok". There are definitely files that contain `:` in their filename so this would complicate the search and appears wrong to me from usability perspective (search query contains result modifier). Maybe some Greasemonkey script would be better place for this.
