### ISSUE TITLE
authorization check at file/document level

### ISSUE THREAD

**Issue by rtyag3** [oracle/opengrok#2042]
Project/Group level authorization does not really guarantee that an "authorized" user will have access to all files/results from within the project/group.

Is there a way to extend this authorization check on a file/document level
isAllowed( Request request, File file )

This would filter out the search results to only those files that a logged in user has read access on.

**Comment by vladak** [comment]
Can you give an example of where the project/group access does not work ? What do you mean by "read access" ?

**Comment by rtyag3** [comment]
>>What do you mean by "read access" ?
I meant file read permissions.

>>Can you give an example of where the project/group access does not work ?
A user who does not have file read permissions to some files in a project, can still search across and read these files.

**Comment by vladak** [comment]
So, is the server switching to the identity of the authenticated user or simply the permissions are set so they do not allow read access ? Trying to understand your use case, maybe you can explain it in detail.

**Comment by rtyag3** [comment]
>>maybe you can explain it in detail.

Data-root is /home/my_data which on a unix filer. So it is already backed up by unix permissions, what ever they are.

/home/my_data/project-1
/home/my_data/project-2

Now, i create a Opengrok index for the above data and deploy a opengrok instance on a server ( //localhost:8080/source ).

I distribute this link across my team, so that they can take benefit out of pre indexed data.

That's where i think i uncovered a security hole.

Lets say there is a file /home/my_data/project-1/read_by_me_only with permissions 600 ( only i can read this file). While indexing the entire my_data, this file also got indexed and now any user who logs in to the //localhost:8080/source can

1. search for text in this file
2. read this file from //localhost:8080/xref/

Neither DL authorization, project/group level authorization can save me from this security hole.

**Comment by vladak** [comment]
What application server do you use ? How is authentication performed ? How
does the opengrok authorization config look ?

Dne 14. 3. 2018 11:26 dop. napsal uživatel "rtyag3" <
notifications@github.com>:

maybe you can explain it in detail.

Data-root is /home/my_data which on a unix filer. So it is already backed
up by unix permissions, what ever they are.

/home/my_data/project-1
/home/my_data/project-2

Now, i create a Opengrok index for the above data and deploy a opengrok
instance on a server ( //localhost:8080/source ).

I distribute this link across my team, so that they can take benefit out of
pre indexed data.

That's where i think i uncovered a security hole.

Lets say there is a file /home/my_data/project-1/read_by_me_only with
permissions 600 ( only i can read this file). While indexing the entire
my_data, this file also got indexed and now any user who logs in to the
//localhost:8080/source can

   1. search for text in this file
   2. read this file from //localhost:8080/xref/

Neither DL authorization, project/group level authorization can save me
from this security hole.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/oracle/opengrok/issues/2042#issuecomment-372973309>,
or mute
the thread

**Comment by rtyag3** [comment]
>>What application server do you use ?
Apache Tomcat 8

>>How is authentication performed ? How
does the opengrok authorization config look ?

Like i mentioned before, i cannot write an appropriate auth plugin **unless the authorization design allows me finer control over the files within a project**

First of all, do you see a potential security hole in the my use-case. Please suggest if a plugin can be designed using the current opengrok release which can cover that.

**Comment by vladak** [comment]
The container servers employ threads to process incoming requests in order to be efficient. The threads run in common process, therefore sharing the identity. For example in Solaris, the Tomcat 8 server runs under the `webservd` user/group so this identity will be checked for all threads processing the requests when performing discretionary access control verification. For this to work, after the user authenticates, the identity of the server would have to be switched. In such implementation this is not possible because there is just single process and the threads share its identity. In sum, employing file level access controls to perform authorization does not fit into the design of container servers. Even if the server was using separate process for handling each request, I'd say this is not a good design anyway as the configuration of the OpenGrok webapp is more and more centralized so this would be a departure from this idea. If you insist that the authorization access checks need to be done on per-file/directory level, with configuration stored in the authorization stack, then we can discuss this in separate issue however I believe our opinion is this is undesirable and would lead to unnecessary complexity.
