### ISSUE TITLE
javadoc:javadoc maven build fails due to inability to resolve the jrcs dependency

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2063]
The javadoc check that is currently running in `before_script` in Travis using the `mvn javadoc:javadoc` command fails on macOS builds. It also started failing on Linux after I did some changes to Maven files:

```
[ERROR] Failed to execute goal on project opengrok: Could not resolve dependencies for project org.opensolaris.opengrok:opengrok:jar:1.1-rcZ: Could not find artifact org.opensolaris.opengrok:jrcs:jar:1.1-rcZ in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```

Full log is e.g. on https://travis-ci.org/vladak/OpenGrok/jobs/365625650

I think the javadoc should be run automatically in one of the Maven phases (`verify`) and not explicitly.

**Comment by tarzanek** [comment]
I completely agree, it didn't run inside verify but it did run standalone so I just run it like that
(there was some problem and since maven wasn't a priority there I didn't investigate)
I think other targets had such problem too, I had documented some of the working or failing targets in helius maven job, check description, ev. paste it here
