### ISSUE TITLE
compile in suggester fails due to missing checkstyle/fileheader.txt

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2223]
When `mvn compile` is run in the `suggester` directory, it fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (checkstyle) on project suggester: Failed during checkstyle configuration: cannot initialize module Header - illegal value 'checkstyle/fileheader.txt' for property 'headerFile' of module Header: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: checkstyle/fileheader.txt -> [Help 1]
```

**Comment by Orviss** [comment]
I found this <https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html> and <https://stackoverflow.com/questions/3414440/how-to-use-maven-checkstyle-plugin-in-multi-module-project>. However, I do not think creating a new module just because of checkstyle is the way to go. I would rather delete the checkstyle than to do it. I will try to look into it futher.

**Comment by vladak** [comment]
If the checkstyle plugin has this limitation/intention/design, then I'm afraid that it will have to be moved to separate module. Having checkstyle is more important than having "clean" module structure I think.
