### ISSUE TITLE
IndexDatabase path issue

### ISSUE THREAD

**Issue by gtoph** [oracle/opengrok#2315]
Looks like recent change broke windows.  Search result links wont work as there is a mix of slashes now:
/source/xref\project\\sub dir 1\\sub dir2\\file

--  String path = parent + '/' + file.getName();
++ String path = parent + File.separator + file.getName();

Changing it back fixes things after re-indexing.

**Comment by vladak** [comment]
The change happened in cset 9489792c.

**Comment by vladak** [comment]
The trouble is that the `path` variable is used for both path constructions (e.g. in `getXrefWriter()` called from `addFile()` called from `indexParallel()` with members of `IndexFileWork` and also in `populateDocument()`) and stored in the index (in the `QueryBuilder.PATH` field). The `File` object construction still works on Windows even after this change because its file API treats forward slashes as file separators (https://stackoverflow.com/questions/4845866/java-on-windows-prevent-slash-in-file-name-from-acting-as-a-separator).

**Comment by gtoph** [comment]
Something still not quite right with the fix.
I didn't have time to debug it, but I noticed that the repository doesn't list on the main page.  If I just put the slash back in, I see it.  
This is what I'm referring to:

![repo](https://user-images.githubusercontent.com/22400253/44927708-53ae2500-ad0a-11e8-806e-4f3787d3e935.jpg)

**Comment by vladak** [comment]
How does this look in the HTML source ?

Dne pá 31. 8. 2018 19:41 uživatel gtoph <notifications@github.com> napsal:

**Comment by vladak** [comment]
Filed #2335 to track this.

**Comment by gtoph** [comment]
Yes, all the xref links seemed to be ok.

**Comment by gtoph** [comment]
I'll have to put things back and view the source, but probably can't until
next week.

**Comment by gtoph** [comment]
Gave it a 5 min debug.   in repos.jspf, repositories are returning zero for some reason from this:

`Set<Project> repositories = pHelper.getUngroupedRepositories();`
