### ISSUE TITLE
add configuration tunable to enable navigation window for every project

### ISSUE THREAD

**Issue by brightchuh** [oracle/opengrok#2397]
Dear opengrok developers,

As mentioned in the title, How to turn on navigation window for every project by default? Thanks a lot!

**Comment by brightchuh** [comment]
Got it! Keep watching.

**Comment by vladak** [comment]
This issue needs to remain open so someone can actually implement this.

**Comment by vladak** [comment]
Also, pull requests are welcome. See https://github.com/oracle/opengrok/blob/master/CONTRIBUTING.md

**Comment by tulinkry** [comment]
We used to have this and then we switched for per project management and it moved to the project class.

One could achieve it with the rest api:
1. Download list of all projects (GET /api/v1/projects)
2. Process the list and update the configuration for the project with navigation enabled (PUT /api/v1/configuration/project1/navigationWindowEnabled)

**Comment by tulinkry** [comment]
So maybe a new endpoint setting the property for all projects would be sufficient.

**Comment by vladak** [comment]
I'd rather do it properly - i.e. have a tunable in `Configuration` (for using it in read-only config) that can be overridden on per-project basis.

**Comment by brightchuh** [comment]
Actually, i think just a little change is needed in the read-only configuration file.
```
  <void property="projects">
   <void method="put">
    <string>PROJECT_NAME</string>
    <object class="org.opengrok.indexer.configuration.Project">
     <void property="navigateWindowEnabled">
      <boolean>true</boolean>
     </void>
    </object>
   </void>
  </void>
```
How about changing string **PROJECT_NAME** here into a **pattern** element, just like what we do in "Project-groups" WIKI Page: "**opengrok.*|apache-.***".
```
    <void method="addGroup">
        <object class="org.opengrok.indexer.configuration.Group">
            <void property="name">
                <string>java</string>
            </void>
            <void property="pattern">
                <string>opengrok.*|apache-.*</string>
            </void>
        </object>
    </void>
```
So that if we want navigation window enabled for all projects by default, we just need to fill **PROJECT_NAME** with wild card **".*"**

**Comment by vladak** [comment]
This approach would not work - the XML snippet above is part of Java bean, i.e. it will get converted into `put` method call with the `Project` object. So, the pattern would become property of single project only.

Instead of introducing `Configuration` boolean tunable which can be overridden on per project basis we can probably make this a pattern in `Configuration` that would be applied to `Project` object instances, setting their boolean values, when they are conceived.

For now, I opted for the simpler yet quite flexible solution that is in line with what is currently done with other per project properties.

Of course, pull requests are always welcome.
