### ISSUE TITLE
"Did you mean" box settings for long term missing in 1.1

### ISSUE THREAD

**Issue by Teriand** [oracle/opengrok#2621]
Continue #2618 
OpenGrok 1.1.2
 "Did you mean" box show hint for small message like 'getmessages' and dont show for long like 'getmessagesgrouped'

![image](https://user-images.githubusercontent.com/26705069/51110528-13a79480-180a-11e9-8fa0-38412888ac0a.png)

![image](https://user-images.githubusercontent.com/26705069/51110545-1e622980-180a-11e9-9d7b-5d94a1fb90cc.png)

**Comment by vladak** [comment]
Also, the hints functionality does not seem to be tested at all.

**Comment by vladak** [comment]
I tried to reproduce this by creating a sample project with a single C file:
```C
void
GetMessagesGrouped(char *a)
{
        printf("foo");
}

int
getMessages(long b)
{
        return (42);
}
```

Performing the searches for lowecase definitions, the reported behavior is observed.

**Comment by vladak** [comment]
﻿﻿﻿For the record, this is how the `checker` object looks like in `searhHelper#getSuggestion()`:
![checker](https://user-images.githubusercontent.com/2934284/51186311-a400da80-18d9-11e9-9ed2-b45b1b5ea15e.jpeg)
Indeed, the Lucene function https://lucene.apache.org/core/7_5_0/suggest/org/apache/lucene/search/spell/SpellChecker.html#suggestSimilar-java.lang.String-int-org.apache.lucene.index.IndexReader-java.lang.String-org.apache.lucene.search.spell.SuggestMode- returns 0 words so the hints are empty.

**Comment by vladak** [comment]
I tried to override the default `accuracy` by setting it to 0.1 (so that it is within the allowed range - https://lucene.apache.org/core/7_5_0/suggest/org/apache/lucene/search/spell/SpellChecker.html#setAccuracy-float-) of the checker by using specific `checker.suggestSimilar()` API (https://lucene.apache.org/core/7_5_0/suggest/org/apache/lucene/search/spell/SpellChecker.html#suggestSimilar-java.lang.String-int-org.apache.lucene.index.IndexReader-java.lang.String-org.apache.lucene.search.spell.SuggestMode-float-) that allows that however there was no change in result.

I'd suggest to the isolate this into standalone test case and then bring it up on the Lucene developers mailing list. This does not seem to be related to OpenGrok directly.

**Comment by Teriand** [comment]
ok, u write link to issue  the Lucene developers?
