### ISSUE TITLE
commandsequence.py#check() should match the error strings more precisely

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2845]
```
Command output in project 'xxxxxx-yyyyyy-apierrors' contains errors:
  opengrok-mirror --loglevel INFO -c /var/opengrok/etc/mirror-config-generated.yml --incoming -U http://localhost:8080 xxxxxx-yyyyyy-apierrors
    output of ['/usr/local/bin/git', 'pull', '--dry-run']:
    
    No incoming changes for repositories in project xxxxxx-yyyyyy-apierrors

```

Check for errors in output could be a little misleading with projects containing the "errors" in the name. Not a big deal but the check could be a little clever.

**Comment by vladak** [comment]
Maybe the check should not be there at all.

**Comment by ktulinger** [comment]
Yes, also an option.

**Comment by tulinkry** [comment]
Yes, also an option.

**Comment by vladak** [comment]
Too bad I don't remember the use case. It is probably something I thought might be useful because I saw it in the Python scripts wrapping over Solaris builds - they match the output from all compilers/linkers/utilities/checker for patterns like this and fail the build. In ideal world, the errors from the commands should be propagated all the way.

**Comment by vladak** [comment]
Possibly, the check can be changed to be case sensitive and match stuff like `ERROR[:]\s+` or such.
