### ISSUE TITLE
too many Perforce queries when indexing

### ISSUE THREAD

**Issue by pavanpenmetsa** [oracle/opengrok#2919]
Hello,
   I am using tomcat9 , opengrok 1.2.23, ubuntu 18

   The opengrok index with history works great but it is putting lot of load on P4 node and sometimes opengrok process is getting stuck due to timeout. Is there a way to slow down the opengrok P4 query (limiting query or threads) which are used to generate history such as "p4 dirs ..." "p4 changes -t ..." which seem to be adding load on p4 node and timing out.

**Comment by vladak** [comment]
There is no rate limiting mechanism. The question is whether p4 repository
needs to perform all these queries. In other words - is this the nature of
p4 itself or just a bad implementation of p4 handling in OpenGrok ? Could
you summarize somehow these queries ? What do they do ? Are they perhaps
per file ? Do these happen for every changed file or simply for all files
in the repository ? Is the load related to the size of the changes in the
repo since the last update ?

Dne čt 5. 9. 2019 17:14 uživatel pavanpenmetsa <notifications@github.com>
napsal:
