### ISSUE TITLE
Merged text after adding OpenGrok logo to header

### ISSUE THREAD

**Issue by baselz324** [oracle/opengrok#3452]
I have added to pageheader.jspf OpenGrok logo to easily return home, but I have this merged text in any source, (merging of list details and menu), could you please tell me where to add an empty div to resolve this?
![image](https://user-images.githubusercontent.com/77238449/110233829-66cf8a80-7f2f-11eb-8bc5-48e0d4d4b197.png)

this line have been add to pageheader.jspf
`<a href="<%= request.getContextPath() %>/"><span id="MastheadLogo"></span></a>`

I have added the logo because it's easier and users are regular for all websites to click on the logo to go back to the homepage, so I suggest adding it into new versions.

**Comment by vladak** [comment]
Changing the JSP files is not recommended/supported. If you want to insert anything into the header/footer, use the include files as documented on https://github.com/oracle/opengrok/wiki/Webapp-configuration#include-files

As for changing the default pages to include the logo also at the top: we strive to keep the UI as minimal as possible so that will not likely happen. There is the 'Home' link that can take users to the index page.

**Comment by baselz324** [comment]
@vladak thnx for your help but it didn't help, the text still merging

**Comment by vladak** [comment]
Don't have any advice right now besides exploring the existing HTML layout. I remember @blu28 was trying to achieve something similar in the past.

**Comment by baselz324** [comment]
@vladak yes I have fixed it by exploring the HTML and editing it and CSS

Thank you

**Comment by blu28** [comment]
This problem always seems like it is a flaw in the CSS layout of the page. I don't know enough CSS to fix it though. My son probably does, I will see if I can get him to take a look.

**Comment by baselz324** [comment]
@blu28 I think I have fixed it under CSS also thank you, I could share my solution if needed.

**Comment by blu28** [comment]
Please.
