### ISSUE TITLE
Cannot coexist 1.7.1 war files and 1.7.2 war files

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#3568]
We have multiple war files under webapps directory of tomcat. Each war file contains one branch/project.
If the tomcat is running with all 1.7.1 war files, adding 1.7.2 war file does not work. This new 1.7.2 war file does not work.
If the tomcat is running with all 1.7.2 war files, adding 1.7.1 war file does not work, too. This new 1.7.1 war file doe not work, too.

tomcat: 10.0.2
jdk: 11.0.2

**Comment by ahornace** [comment]
Well, having one Tomcat for serving multiple war files is the way of the past and we do not want to support that. It's inherently bad as the resources are shared and there is no way to control it. 

That's why newer Java webapps have the servlet container embedded.

If you want to use a deployment like mentioned above, then please use the same version for all.

**Comment by ahornace** [comment]
Just for completion, likely caused by https://github.com/oracle/opengrok/pull/3561 and shared classloader
