### ISSUE TITLE
History and Annotate links not working

### ISSUE THREAD

**Issue by AmeyaBhujbal** [oracle/opengrok#3576]
History and annotate links are not working. After checking the logs of catalina, it says "Failed to instantiate internal repository data for Perforce" and "done invalidating 0 repositories" even though there are repositories.

History cache is getting generated, but the link is still not working.

Below mentioned is the content from **catalina.out** log:-
org.opengrok.indexer.history.HistoryGuru.lambda$invalidateRepositories$5 Failed to instantiate internal repository data for Perforce in (directory path)
org.opengrok.indexer.util.Statistics.logIt done invalidating 0 repositories (took 445 ms)

Below mentioned is the content from **opengrok** log:-
2021-05-05 14:01:06.240+0530 INFO t1 Statistics.logIt: Done scanning for repositories, found 7 repositories (took 0:01:52)
2021-05-05 14:01:06.240+0530 INFO t1 Indexer.prepareIndexer: Generating history cache for all repositories ...
2021-05-05 14:01:06.257+0530 INFO t1 HistoryGuru.createCacheReal: Creating historycache for 7 repositories

In OpenGrok log, number repositories are being detected correctly, but not the same case with Tomcat log.

I am using OpenGrok 1.7.2, 
Apache Tomcat 10.0.5, 
JDK 11.0.7,
Linux/unix system.

**Comment by vladak** [comment]
Has this ever worked ? Is this just about Perforce repositories ? Do you perhaps have other projects based on another VCS type (Git, Mercurial, ...) that work fine in this respect ?

The web app needs to be able to execute Perforce commands in order to perform repository invalidation. If the `p4` command is in location that Tomcat cannot readily find,  this is done by passing Java option. For Perforce that would be `-Dorg.opengrok.indexer.history.Perforce=/path/to/p4`. For Tomcat this is done by adding them to `JAVA_OPTS` environment variable defined in `setenv.sh` located in `CATALINA_BASE/bin`.

**Comment by vladak** [comment]
For the record I added https://github.com/oracle/opengrok/wiki/Webapp-configuration#java-system-properties

**Comment by AmeyaBhujbal** [comment]
Added **JAVA_OPTS** to sentenv.sh in CATALINA_BASE/bin and it got working.
The issue is fixed, It really helped a lot.  
Thankyou so much!
:)

**Comment by vladak** [comment]
#499 would have solved this, I think.
