### ISSUE TITLE
search API def return more than needed

### ISSUE THREAD

**Issue by chkp-baselz** [oracle/opengrok#3748]
Hey,
My Opengrok version is 1-5-11
When I try to search for definitions I got each appears on the file the variable is defined there, for example,
`https://opengrok.checkpoint.com:8443/source/api/v1/search?def=ws_http2_stream_error_action&projects=ivory_main`
This is what I get, it should return only line 105, on UI it works and jumps me direct to line 105
```json
{
  "time": 11,
  "resultCount": 1,
  "startDocument": 0,
  "endDocument": 0,
  "results": {
    "/ivory_main/ws/http2/ws_http2_parser.c": [
      {
        "line": " * fw ctl set int <b>ws_http2_stream_error_action</b> 0/1",
        "lineNumber": "103"
      },
      {
        "line": "int <b>ws_http2_stream_error_action</b> = E_WS_HTTP2_STREAM_ERROR_HANDLE;",
        "lineNumber": "105"
      },
      {
        "line": "\t\tswitch(<b>ws_http2_stream_error_action</b>)",
        "lineNumber": "5009"
      },
      {
        "line": "\t\t\t\tWS_DEBUG(WS_HTTP2, WS_ERROR, (\"invalid stream error action %d\", <b>ws_http2_stream_error_action</b>));",
        "lineNumber": "5035"
      }
    ]
  }
}
```

**Comment by vladak** [comment]
Getting the results of search to the client is actually pretty complex.

There are major differences in how the search is done in the UI and via the API. I will try to summarize it here for future reference since I don't know whole lot about it myself.

When going via the API, it starts in `SearchController#search()`. This uses `SearchEngineWrapper`, a private static class located in the same source code file. As suggested by the name, this class is a wrapper to the `SearchEngine` class. The `search()` method then calls `engine.search()` (where `engine` is instance of `SearchEngineWrapper`) which returns the list of `Hit` objects which are then wrapped inside the `SearchResult` object and this gets converted automatically to the JSON representation returned to the client.

Now, for the context (sic!) of this bug, `SearchEngineWrapper#search()` calls `SearchEngine#search()` to get the search results and then calls `SearchEngine#results()` to convert the search results to the list of `Hit objects. The `SearchEngine` object keeps the list of hits in an array of `ScoreDoc` (Lucene) objects. The `SearchEngine#results()` traverses this array and in this particular case uses the `Context#getContext()` that fills the list of `Hit` objects: https://github.com/oracle/opengrok/blob/33eb38aca843b8fd755b6af7e4df6a5289616a6d/opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java#L467-L476

This method then uses `PlainLineTokenizer`: https://github.com/oracle/opengrok/blob/33eb38aca843b8fd755b6af7e4df6a5289616a6d/opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/Context.java#L364 which might adds `Hit` objects to the list in `dumpRest()`: https://github.com/oracle/opengrok/blob/33eb38aca843b8fd755b6af7e4df6a5289616a6d/opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/Context.java#L404-L406 https://github.com/oracle/opengrok/blob/33eb38aca843b8fd755b6af7e4df6a5289616a6d/opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/Context.java#L435 which in this case is actually unwanted.

**Comment by vladak** [comment]
The use of `Context` to present the results from the `/search` API call likely leads to problems such as #2612, #3090, #3170.
