### ISSUE TITLE
Whether the index can be partially updated

### ISSUE THREAD

**Issue by KelsonHoole** [oracle/opengrok#3903]
I used the -P to generate indexes for each directory.However, only one folder has code changes. I hope that when the index is generated, I can just specify this directory to accelerate index gereration.

**Comment by vladak** [comment]
Is the project tracked by a Version Control System ? (such as Git)

**Comment by KelsonHoole** [comment]
来信已收到____胡科

**Comment by KelsonHoole** [comment]
Yes,I use this command to create index:
$JAVA -jar ${OPENGROK_DIR}/lib/opengrok.jar  -c ${CTAGS_PATH} -W ${OPENGROK_DIR}/data/configuration.xml -P -v -s ${OPENGROK_DIR}/src/ -d ${OPENGROK_DIR}/data --progress

However, every time I use this command, all folders are scanned. I want to scan only the specified folders the second time.

**Comment by vladak** [comment]
This is not supported currently. It depends on your use case. If you are interested in files changed by a commit(s) then #3077 will help, once implemented. Otherwise (specifying list of directories/files explicitly), there are no plans, although some sort of piggybacking on top of the VCS solution could be possible.

**Comment by vladak** [comment]
The feature is not implemented yet.

**Comment by vladak** [comment]
closing as dup of #3077 given there are no plans to implement custom list of files/dirs.

**Comment by KelsonHoole** [comment]
来信已收到____胡科
