### ISSUE TITLE
symbols comes twice in opengrok with Project configuration

### ISSUE THREAD

**Issue by abhi31oct** [oracle/opengrok#3904]
I am setting up an opengrok with two project with different version (**sudo opengrok-projadm -b /opengrok -a Hello**) and (**sudo opengrok-projadm -b /opengrok -a Hello_v1**) And index the project individually -

```
sudo opengrok-indexer -a /opengrok/dist/lib/opengrok.jar -- \
    -c /usr/local/bin/ctags \
    -U 'http://localhost:8080/source' \
    -R fresh_config.xml \
    -s /opengrok/src -d /opengrok/data -H -P -S -G \
    -W /opengrok/etc/configuration.xml \
    -H Hello \
    Hello

sudo opengrok-indexer -a /opengrok/dist/lib/opengrok.jar -- \
    -c /usr/local/bin/ctags \
    -U 'http://localhost:8080/source' \
    -R fresh_config.xml \
    -s /opengrok/src -d /opengrok/data -H -P -S -G \
    -W /opengrok/etc/configuration.xml \
    -H Hello_v1 \
    Hello_v1
```

Everything is fine, I am facing only one issue, each symbol appears twice in search results.

![opengrok1](https://user-images.githubusercontent.com/11948352/157725797-6af9e27c-f85c-4983-8b27-b45c2b394af9.PNG)

Any idea why duplicate entries are coming in search results, I am using Release - 1.7.30, and Tomcat 10.

**Comment by vladak** [comment]
Replicated the problem using https://github.com/githubtraining/hellogitworld - this seems to be caused by the way how the indexer is run. If I index all the projects at once, then the problem does not happen. Similarly, if I index the projects separately using the OpenGrok Docker image, it does not happen.

There is something in the command line options used that results in multiple Lucene documents to be created for the files in question - tracing the results of https://github.com/oracle/opengrok/blob/5b802c5825ff40112b513b9f6ef7e31b3b5aa4c7/opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java#L495-L497 I can see the `ScoreDoc` array to have 2 items there, each with different document Id.

While I could debug the indexer some more to see why this particular invocation leads to multiple documents created for given file, the fix here is to use proper per-project workflow as highlighted on https://github.com/oracle/opengrok/wiki/Per-project-management-and-workflow or use the Docker image that does it under the covers.

Specifically, per project indexed should not use the `-W` and `-S` options.

**Comment by vladak** [comment]
Looking at the differences in sizes for the Lucene index files for given project, I can see the "per-project" reindex (putting this to quotes on purpose because this is not how per project reindex should be run) producing larger files than all-project reindex does:

![botched_perproj-vs-full_reindex](https://user-images.githubusercontent.com/2934284/157864037-32fedad8-be95-4221-9b62-11266c51b528.png)

These are block sizes as reported by `ls`. Also the sizes of the index files produced by the Docker image match those produced by the full reindex (12, 8, 8, 4, ...).

**Comment by vladak** [comment]
Looking into the indexes with Luke, keeping the sides to match the above vimdiff:

![luke-full-vs-botched](https://user-images.githubusercontent.com/2934284/157867356-b6f7ff77-83c2-4d93-85d9-21b3667b949d.png)

the botched per project reindex has 57 documents versus 29 documents for the case when the index was created using full reindex.

Performing the search for `path:Sum` within Luke confirms - for the botched index one gets 2 documents in the results, for the sound index just one document. Looking at fields of the 2 returned documents in the botched index, they seem to be identical. The question is what made the indexer to create the second document.

**Comment by vladak** [comment]
The file in question (and all files) is being added twice for the botched reindex:
```
$ grep 'Add.*Sum\.groovy' /tmp/index-part.out
14:15:37 FINE: Add: /Hello/src/Sum.groovy (PlainAnalyzer)
14:15:37 FINER: Added: /Hello/src/Sum.groovy (PlainAnalyzer)
14:15:37 FINE: Add: /Hello/src/Sum.groovy (PlainAnalyzer)
14:15:37 FINER: Added: /Hello/src/Sum.groovy (PlainAnalyzer)
```
hence 2 documents will get created for it.

The trouble is that the `subFiles` argument of the `doIndexerExecution()` https://github.com/oracle/opengrok/blob/5b802c5825ff40112b513b9f6ef7e31b3b5aa4c7/opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java#L1072 contains 2 entries: "/Hello" and "/Hello". This will in turn lead to the index being updated twice.

This is caused by repeating the `Hello` argument:
```
-H Hello \
    Hello
```
and the arguments being held in a list.

**Comment by abhi31oct** [comment]
I have validated the fix, It is working fine now. Thanks!
