### ISSUE TITLE
Still dups in search with 1.9.4

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#4317]
Hi @vladak 

On one of my PRD OG instance, I have installed 1.9.4 and reindexed everything from scratch.
Users report they still have  dups when searching :-(
Same issue on another UAT instance running 1.9.4 where a user found dup (after he found first a dup on the related (I mean, same code is indexed) PRD one running 1.7.35).

What could I do to try to understand the issue?

**Comment by vladak** [comment]
Firstly, it would help to get more information about the dups, i.e. quantify them and see how they change over time. Ideally track when they started appearing after the reindex from scratch, esp. w.r.t. periodic reindex events.

**Comment by ChristopheBordieu** [comment]
Very difficult for me to quantify the number of dups and when they start to appear, because of the size of the data indexed.

On a case that has been reported on my UAT.
I see no dup on history cache. This is a good point since on PRD (1.7.35) I have plenty of dups for history cache for the file.
```
opengrok@[uat-1.94]:/srv/opengrok-var/historycache/QWERTY/azerty$ zgrep -A 1 '<void property="revision">' Forest.xml.gz  | grep string | sed -e 's/<string>//' -e 's/<\/string>//' | sort | uniq -c | grep -v " 1 " | wc -l
0
```
```
opengrok@[prd-1.7.35]:/srv/opengrok-var/historycache/QWERTY/azerty$ zgrep -A 1 '<void property="revision">' Forest.xml.gz  | grep string | sed -e 's/<string>//' -e 's/<\/string>//' | sort | uniq -c | grep -v " 1 " | wc -l
55
```

What I don't understand is the data regarding number of commits on the file duplicated:
```
opengrok@[uat-1.94]:/srv/opengrok-src/QWERTY/azerty$ git log --oneline --merges -- Forest.xml | wc -l
116
opengrok@[uat-1.94]:/srv/opengrok-src/QWERTY/azerty$ git log --oneline -- Forest.xml | wc -l
1154
opengrok@[uat-1.94]:/srv/opengrok-src/QWERTY/azerty$ cd -
/srv/opengrok-var/historycache/QWERTY/azerty
opengrok@[uat-1.94]:/srv/opengrok-var/historycache/QWERTY/azerty$ zgrep -A 1 '<void property="revision">' Forest.xml.gz  | grep string | sed -e 's/<string>//' -e 's/<\/string>//' | sort | wc -l
1112
```

1154-116=1038 so I would have expected 1038 different commits into history cache file.

**Comment by ChristopheBordieu** [comment]
When searching, Tomcat logs for file duplicated:
```
26-Apr-2023 16:24:01.976 FINEST [http-nio-8080-exec-5] org.opengrok.indexer.search.Results.createMap 12,602: /QWERTY/azerty/Forest.xml
26-Apr-2023 16:24:01.976 FINEST [http-nio-8080-exec-5] org.opengrok.indexer.search.Results.createMap 12,773: /QWERTY/azerty/Forest.xml
```

**Comment by ChristopheBordieu** [comment]
My mistake... I closed the issue.

**Comment by vladak** [comment]
Is `QWERTY` a Git repository ? What settings are enabled for it ? (esp. merge commits, renamed files)

As for the discrepancy between the `git log` output and the history cache, it is not always 1-1 because the way how the history cache is constructed - getting the history for the top level directory of given repository and then creating a reverse hash map (file -> list of commits) to store the history cache entries for individual files. I commented about that recently in a discussion, cannot find it right now.

**Comment by vladak** [comment]
Also, what do the changes for `/QWERTY/azerty/Forest.xml` look like ? The contents of the file are not relevant, I am after how it is being changed in terms of changesets.

Given that I am not able to reproduce this locally, I will need some extensive logging and problem pinpointing on your side.

**Comment by vladak** [comment]
I'd propose the following strategy for identifying the pattern that leads to the duplicate documents:
  - setup a separate test environment with just a single project (where the dups were detected in the past)
  - increase the log level for the indexer to `FINEST`, use a logging configuration that maintains separate log file for each indexer run and keeps the log files from rotating away
  - run the indexer check after each indexing using the `--checkIndex documents`

As for the mirroring, one way would be to let it run organically, i.e. let the incoming changes to the repository brought in as they happen in the origin. The alternative would be to start in a certain changeset in the repository and add bunch of changesets at a time, followed by reindex and index check. Repeat until there are duplicates in the index.

**Comment by tchik93** [comment]
This is happenning in the OpenGrok version 1.12.12. I will try to provide you the details asked in the previous comment.

**Comment by vladak** [comment]
Managed to replicate the problem with https://github.com/oracle/solaris-userland/ using this script (needs #4535 to avoid failing due to zero live documents on the initial indexing):
```bash
#!/bin/bash

#
# attempt to reproduce https://github.com/oracle/opengrok/issues/4317
#
# based on git-commit-hopping.sh but with added randomness

# set -x
set -e

repo_url="https://github.com/oracle/solaris-userland/"
initial_rev=32c0d9faed7b049872ca9bd78f9bf3e901cff482	# from 2022

src_root="/var/tmp/src.opengrok-issue-4317"
data_root="/var/tmp/data.opengrok-issue-4317"

# Assumes built OpenGrok.
function run_indexer()
{
        # TODO: store the log somewhere
        java -cp '/home/vkotal/opengrok-vladak-scratch/distribution/target/dist/*' \
            org.opengrok.indexer.index.Indexer \
            -c /usr/local/bin/ctags \
	    --economical \
            -H -S -P -s "$src_root" -d "$data_root" \
	    -W "$data_root/config.xml" \
	    >/dev/null 2>&1

	java -cp '/home/vkotal/opengrok-vladak-scratch/distribution/target/dist/*' \
            org.opengrok.indexer.index.Indexer \
	    -H \
	    -R "$data_root/config.xml" \
	    --checkIndex documents
}

function get_next()
{
	ids=( $(git log --oneline --reverse ..origin/master | awk '{ print $1 }') )
	size="${#ids[@]}"
	modulo=16
	if (( size == 0 )); then
		echo ""
		return
	fi
	if (( modulo > size )); then
		modulo=$size
	fi
	n=`expr $RANDOM % $modulo`
	if (( n == 0 )); then
		n=1
	fi
	echo ${ids[$n]}
}

project_root="$src_root/solaris-userland"
if [[ ! -d $src_root ]]; then
	echo "Cloning $repo_url to source root"
	git clone $repo_url "$project_root"
fi

echo "Removing data root"
rm -rf "$data_root"

cd "$project_root"
git checkout "$initial_rev"

while [[ 1 ]]; do
	rev=$(get_next)
	if [[ -z $rev ]]; then
		break
	fi
	echo "Checking out $rev"
	git checkout -q $rev
	run_indexer
done
```
It ended after just 4 iterations with:
```
Jan 26, 2024 6:42:55 PM org.opengrok.indexer.index.IndexCheck checkProjectsParallel
WARNING: index check failed
index '/var/tmp/data.opengrok-issue-4317/index/solaris-userland' failed document check: duplicate paths = {/solaris-userland/components/python/pyasn1-modules/Makefile=2}
	at org.opengrok.indexer.index.IndexCheck.checkDocuments(IndexCheck.java:590)
	at org.opengrok.indexer.index.IndexCheck.checkDir(IndexCheck.java:274)
	at org.opengrok.indexer.index.IndexCheck.checkDirWithLogging(IndexCheck.java:244)
	at org.opengrok.indexer.index.IndexCheck.lambda$checkProjectsParallel$0(IndexCheck.java:152)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
which matches my internal observations.

**Comment by vladak** [comment]
The cause of the above is that in the last reindex for changeset 87ffc28c4, the list of files returned from the `FileCollector` contained 2 similar paths, **in this order**:
  - `/solaris-userland/components/python/pyasn1-modules/Makefile`
  - `/solaris-userland/components/python/pyasn1/Makefile`

The ordering of the `uidIter` is reversed, which means when the `uidIter` is on the latter and the former comes in to `processFileIncremental()`, the document is skipped so there is no call to `removeFile()` however is added to the `IndexDownArgs`, leading to the duplicate document.

The trouble lies here: https://github.com/oracle/opengrok/blob/636b3f3255b7eea1f96936833cc178fa43e53a49/opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileCollector.java#L42

Rather than assuming, the set should be returned unsorted and `IndexDatabase` should perform the sorting itself.

**Comment by vladak** [comment]
There is another problem on https://github.com/oracle/opengrok/blob/ba9e18dd7e0a2a4d8fe900b01cb6f84bec8b8cd1/opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java#L1661 - this also needs to compare the paths using path components, not the whole path as string.

**Comment by vladak** [comment]
There is some trickery involved with fixing this. After making sure the paths coming from the `FileCollector` to `IndexDatabase` are properly sorted based on path components and the same comparator is also used when traversing the index in `IndexDatabase#processFileIncremental()`, rerunning a test case multiple times still makes it fail with duplicate documents sometimes.

What seems to be happening in the case when the test fails is that the path that is later identified as duplicate goes through `IndexDatabase#processFileIncremental()` and there is a document with that path that is deleted and so is skipped. There does not seem to be a live document matched for that path in the cycle (something I have yet to verify) so the document is merely added, not updated, leading to the duplicity.

I think the reason this is not 100% reproducible is that the heavy parallelization done in the 2nd phase of indexing leads to different ordering of how documents are added/deleted in the index, possibly leading to segment reduction or lack of. For the cases when the same test passes, there are no deleted documents for the paths that otherwise cause document verification failure in the last reindex.

For the record, here's the test script:
```shell
#!/bin/bash

#
# attempt to reproduce https://github.com/oracle/opengrok/issues/4317
# (more isolation)
#
# based on ~/opengrok-issue-4317.sh sans the randomness.
#
# It tests particular sequence of changes, that **SOMETIMES** leads
# to duplicate documents.
#


set -e

repo_url="https://github.com/oracle/solaris-userland/"

src_root="/var/tmp/src.opengrok-issue-4317"
data_root="/var/tmp/data.opengrok-issue-4317"

# Assumes built OpenGrok.
function run_indexer()
{
        java -cp '/home/vkotal/opengrok-vladak-scratch/distribution/target/dist/*' \
	    -Djava.util.logging.config.file=/var/tmp/logging.properties-opengrok-FINEST_Console \
            org.opengrok.indexer.index.Indexer \
            -c /usr/local/bin/ctags \
	    --economical \
            -H -S -P -s "$src_root" -d "$data_root" \
	    -W "$data_root/config.xml" \
	    >/var/tmp/opengrok-issue-4317-$1.log 2>&1

	java -cp '/home/vkotal/opengrok-vladak-scratch/distribution/target/dist/*' \
            org.opengrok.indexer.index.Indexer \
	    -H \
	    -R "$data_root/config.xml" \
	    --checkIndex documents
}

project_root="$src_root/solaris-userland"
if [[ ! -d $src_root ]]; then
	echo "Cloning $repo_url to source root"
	git clone $repo_url "$project_root"
fi

echo "Removing data root"
rm -rf "$data_root"

echo "Removing logs"
rm -f /var/tmp/opengrok-issue*.log

cd "$project_root"
git checkout -q master

ids="3b039b16f 170ebb43b 80cc6ae18 52c217090 a609ca278 69a8daead 07e01a4e6 154009177 794af3182 c073248f7 823f2c28e 4a5e3cb85 341f9beb2 653378bce 4f8fe9ee8"

for id in $ids; do
	echo "### $id"
	git checkout -q $id
	#if [[ $id != "4f8fe9ee8" ]]; then
	#	run_indexer $id
	#fi
	run_indexer $id
done
```

**Comment by vladak** [comment]
What is causing the latest test failure is uid overlap/clash. For the iteration that leads to the duplicate document, a match for the file is found in `IndexDatabase#processFileIncremental()` however the uid was found in deleted documents so the iteration was short-circuited by the `continue` statement. The cycle should have been through another non-deleted document for the same path, however it was not, because it shared the same uid with the deleted document. The cycle finished and the file was present, therefore `IndexDownArgs` was created, leading to the duplicate document.

The first part of the uid is the path, the second path is the time stamp that is take from the last modified time value of the file. I have yet to figure out whether this is caused by my approach (using `git checkout` to switch to given changeset; maybe I should have used `git reset --hard`) or whether this is inherent to the repository (in which case more fixing would be needed).

**Comment by vladak** [comment]
[Git it does not preserve/restore file time stamps](https://stackoverflow.com/questions/2179722/checking-out-old-files-with-original-create-modified-timestamps) so this behavior is sort of expected. Therefore, the last failure was indeed a cause of sloppy test setup. Detailed analysis is on https://gist.github.com/vladak/351f135c1f9b0ddc979be70ceaa20133. That said, to avoid such corruption in the future (not related to this issue, I believe) I added uid/date check to the history based processing. Running the updated script (below) with indexer that performs the check survived through 16 iterations. With the previous version of the script it failed after handful of iterations.
```bash
#!/bin/bash

#
# attempt to reproduce https://github.com/oracle/opengrok/issues/4317
# (more isolation)
#
# based on ~/opengrok-issue-4317.sh sans the randomness.
#
# v4: touch the files to avoid duplicate uids
#
# It tests particular sequence of changes, that **SOMETIMES** leads
# to duplicate documents.
#


set -e

repo_url="https://github.com/oracle/solaris-userland/"

src_root="/var/tmp/src.opengrok-issue-4317"
data_root="/var/tmp/data.opengrok-issue-4317"

# Assumes built OpenGrok.
function run_indexer()
{
        java -cp '/home/vkotal/opengrok-vladak-scratch/distribution/target/dist/*' \
	    -Djava.util.logging.config.file=/var/tmp/logging.properties-opengrok-FINEST_Console \
            org.opengrok.indexer.index.Indexer \
            -c /usr/local/bin/ctags \
	    --economical \
            -H -S -P -s "$src_root" -d "$data_root" \
	    -W "$data_root/config.xml" \
	    >/var/tmp/opengrok-issue-4317-$1.log 2>&1

	java -cp '/home/vkotal/opengrok-vladak-scratch/distribution/target/dist/*' \
	    -Djava.util.logging.config.file=/var/tmp/logging.properties-opengrok-FINEST_Console \
            org.opengrok.indexer.index.Indexer \
	    -H \
	    -R "$data_root/config.xml" \
	    --checkIndex documents \
	    >/var/tmp/opengrok-issue-4317-$1.check.log 2>&1
}

project_root="$src_root/solaris-userland"
if [[ ! -d $src_root ]]; then
	echo "Cloning $repo_url to source root"
	git clone $repo_url "$project_root"
fi

echo "Removing data root"
rm -rf "$data_root"

echo "Removing logs"
rm -f /var/tmp/opengrok-issue*.log

cd "$project_root"
git checkout -q master
# Establish a common time base line.
find "$src_root/" -type f -exec touch {} \;

ids="3b039b16f 170ebb43b 80cc6ae18 52c217090 a609ca278 69a8daead 07e01a4e6 154009177 794af3182 c073248f7 823f2c28e 4a5e3cb85 341f9beb2 653378bce 4f8fe9ee8"

for id in $ids; do
	echo "### $id"
	git checkout -q $id
	# Git does not preserve/restore file time stamps so simulate a git pull.
	# Ideally this should be done only for the "incoming" files, howerver it suffices for this use case.
	find "$src_root/" -type f -exec touch {} \;

	#if [[ $id != "4f8fe9ee8" ]]; then
	#	run_indexer $id
	#fi
	run_indexer $id
done
```

I am going to modify the original randomness based script and will let it run extended time period to see if this really sticks.
